apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pebqbb0h4-dotnet-basic
  janus-idp.io/tekton: pebqbb0h4-dotnet-basic
  backstage.io/kubernetes-id: pebqbb0h4-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pebqbb0h4-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
